### ISSUE TITLE
Set up to extend to other cities

### ISSUE THREAD

**Issue by beamalsky** [istheweatherweird/itww_bot#17]
and document how! See https://github.com/istheweatherweird/itww_chicago/issues/10#issuecomment-590444570

**Comment by beamalsky** [comment]
Ok I've been thinking about this and I've come around to running all the Twitter accounts from a single Heroku app—the con of keeping all those Twitter API keys  (4 for each bot) straight in one app is outweighed by the pro of not having to manage multiple apps, as @potash was saying. 

My general idea of how this could work is to have a `cities` list in `bot.py` that includes all the current cities we're handling. When bot.py is run it checks each of those. Twitter API key names should be something like the form `<CITY>_KEY_NAME` and be grabbed in turn for each city selected.

Those keys and actual Twitter accounts will still have to be individually created.

**Comment by potash** [comment]
can one email have multiple twitter accounts or do we need to make email addresses like nyc@istheweatherweird.com, etc. ?


 ---- On Tue, 25 Feb 2020 10:59:11 -0600 Bea Malsky <notifications@github.com> wrote ----

**Comment by beamalsky** [comment]
I usually do this with my gmail account using their aliases, where you can add a + and it will automatically forward. Like this: https://thenextweb.com/google/2017/08/17/how-the-plus-sign-can-save-your-gmail-inbox-from-becoming-a-pit-of-doom/

So we could make istheweatherweird@gmail.com, forward to somewhere, and then just use istheweatherweird+[CITY_NAME]@gmail.com to set up accounts

**Comment by potash** [comment]
sounds like a good solution


 ---- On Tue, 25 Feb 2020 17:23:59 -0600 Bea Malsky <notifications@github.com> wrote ----

**Comment by beamalsky** [comment]
This is just about ready to go. What do you think are the top priority cities? Maybe we could start with Chicago, NYC, LA, and Houston

**Comment by potash** [comment]
Chicago, NYC, and Boston get the most traffic on the website but those people don't necessarily use twitter. I'll trust your judgement but definitely Chicago and NYC. Also should the repo be renamed? `itww_twitter` or `istheweatherweird-twitter` or whatever you prefer

**Comment by beamalsky** [comment]
Cool good to know! I changed the name to `itww_bot` before seeing your comment. Does that name work for you?

**Comment by beamalsky** [comment]
Did one of you already grab istheweatherweird@gmail.com? Gmail is telling me it's taken.

**Comment by potash** [comment]
Great




---- On Tue, 03 Mar 2020 11:00:02 -0600 notifications@github.com wrote ----



Cool good to know! I changed the name to itww_bot before seeing your comment. Does that name work for you?

**Comment by potash** [comment]
huh i don't remember doing that but maybe @jsbj does? weirdly when i try to login it says the account doesn't exist (i was trying to see if i could reset password etc).

otoh this email address won't be public, just for creating the twitter accounts right? in that case the name doesn't matter


 ---- On Tue, 03 Mar 2020 11:07:24 -0600 Bea Malsky <notifications@github.com> wrote ----

**Comment by beamalsky** [comment]
Would one of you like to make a gmail account to use for this? I set up 3 new cities with my own email to make getting through the developer application easier, but if you want to switch them at this point we can do that.

**Comment by beamalsky** [comment]
Here's a list with all the new bot accounts! https://twitter.com/i/lists/1235255384014716928

If all goes well, once each city hits 6pm today they should each tweet.

**Comment by potash** [comment]
Exciting




---- On Wed, 04 Mar 2020 11:50:54 -0600 notifications@github.com wrote ----



Here's a list with all the new bot accounts! https://twitter.com/i/lists/1235255384014716928

If all goes well, once each city hits 6pm today they should each tweet.

**Comment by potash** [comment]
Seems to be working, can this be closed?

**Comment by beamalsky** [comment]
Yes!
