### ISSUE TITLE
Consider what happens when NWS API doesn't update

### ISSUE THREAD

**Issue by potash** [istheweatherweird/itww_bot#20]
Re: #19, actually the most likelything to break is the NWS API. It seems to get delayed (not update with new observations) about once every few months. In that case the latest observation is maybe 12 hours old, in which case when the bot fetches we only have data on 12 of the 24 hours in that day. We could

1) Not tweet if there isn't a certain level of coverage in the observations. Then we'd need logic as described in #19 for the bot running later to retry.

2) Use a different weather API on the backend. We considered this on the website but didn't do it because NWS was the only API that didn't need a key. But for backend we can use a key and not expose it to the public and also this is very low traffic so we can use a free key

**Comment by beamalsky** [comment]
If there's a different API you think is more reliable we could definitely switch to that, since we're already dealing with handling keys for Twitter.

**Comment by potash** [comment]
darksky is great but you request a position (lat/lng) not a station (KORD) and it does some additional processing on its temperatures. that's generally a good thing but in this case we want to be careful that the temperatures are all comparable. using NWS for current and NOAA for past has a certain comparability built-in (albeit not perfect either).

doing this well requires some digging and comparing

**Comment by beamalsky** [comment]
Now that we've got tweets about week and day measurements going, I'm thinking I should set up something that checks that the earliest observation from NWS is within X hours of our start time, and if it's not to skip tweeting and send us an error notification. What do you think makes sense for that X value? Maybe like 6 hours?

**Comment by beamalsky** [comment]
I think we can close this now that we're checking with each tweet for big gaps between NWS observations. If that's a consistent problem we should consider switching data sources.
