### ISSUE TITLE
make sentence reflect average temp

### ISSUE THREAD

**Issue by potash** [istheweatherweird/itww_bot#24]
the sentence still mirrors the website but now the quantity is not the current temp but the average in past 24 hours

**Comment by beamalsky** [comment]
What phrasing do you have in mind?

**Comment by potash** [comment]
How about:


The weather in Chicago was (typical|a bit weird|etc) (today|this week|this month|this year). The average temperature was...








---- On Tue, 03 Mar 2020 19:39:30 -0600 notifications@github.com wrote ----



What phrasing do you have in mind?

**Comment by potash** [comment]
Or the second sentence might sound better as


"It was 41dF on average, ..."


That might be what we discussed originally




---- On Tue, 03 Mar 2020 19:39:30 -0600 notifications@github.com wrote ----



What phrasing do you have in mind?

**Comment by beamalsky** [comment]
I like it! I was feeling like the daily tweets should be past tense too.
