### ISSUE TITLE
Add weekly review

### ISSUE THREAD

**Issue by beamalsky** [istheweatherweird/itww_bot#5]
Tweet a weekly recap Sundays at 6pm

**Comment by beamalsky** [comment]
Closed by #22

**Comment by potash** [comment]
Did you check whether the NWS api actually returns a full week of temps?


I assume that there is some limit on how many temps it will return, e.g. I doubt it will do a year. Question is does it fail silently (returning something but not everything)




---- On Tue, 03 Mar 2020 11:02:27 -0600 notifications@github.com wrote ----



Closed by #22

**Comment by beamalsky** [comment]
Ah good point, definitely worth testing. Related to #20, are there any other weather APIs you trust more than NWS?

**Comment by beamalsky** [comment]
We're now testing for this via #28 ! If we get a lot of NWS errors, consider trying a different source as discussed in #20
