### ISSUE TITLE
Use linear interpolation to get daily average

### ISSUE THREAD

**Issue by beamalsky** [istheweatherweird/itww_bot#9]
See https://github.com/istheweatherweird/itww_chicago/blob/master/itww.py#L58

**Comment by beamalsky** [comment]
@potash if you'd like to pick this one up, go for it!

**Comment by beamalsky** [comment]
@potash are you going to pick this one up?

**Comment by potash** [comment]
yes thanks for the reminder, missed it the first time


 ---- On Mon, 24 Feb 2020 16:26:28 -0600 Bea Malsky <notifications@github.com> wrote ----
